### PR TITLE
[Fix] ignore receiver detached from transport

### LINKED ISSUE #51: Ignore receiver when detached from transport
Hello, 

First of all, this library is super cool . 
Lately, I have encountered a small problem that prevented me from using it. 
In case there are transports (single or multiple) but also classes implementing ReceiverInterface without being attached to a transport, the registration of "the transport" is prevented because it implements receiverInterface but not transportInterface. 

For example: 

if I have in config:
````
    Zenstruck\Messenger\Test\Tests\Fixture\Messenger\Receiver\RandomReceiver:
        tags:
            - { name: messenger.receiver }
````

I tried with this test case and i received this type of error
```
self::bootKernel(['environment' => 'with_receiver']);
    $this->expectException(\TypeError::class);
    $this->expectExceptionMessage('Zenstruck\Messenger\Test\Transport\TestTransportRegistry::register(): Argument #2 ($transport) must be of type Symfony\Component\Messenger\Transport\TransportInterface');
$this->messenger();
```

In the compiler pass, the check is based on 
`
$container->findTaggedServiceIds('messenger.receiver')
`
but it does not distinguish if it's a class that just implements ReceiverInterface or TransportInterface
and then, the method call "register" of TestTransportRegistry expects a TransportInterface. 

If it's possible, I would like to suggest a fix. #52 

Thanks again for this library!

### PR DESCRIPTION
**Pull request by alli83**
Hello,

Issue explained here: #51 

summary: In case there are transports (single or multiple) but also classes implementing ReceiverInterface without being attached to a transport, the registration of "the transport" is prevented because it implements receiverInterface but not transportInterface.

Proposal: Check if's a TransportInterface before calling register of testTransportRegistry

### CODE REVIEW

**Comment by kbond** [comment]
Thanks for the fix @alli83!

I'm not familiar with advanced messenger usage. I'm just curious, what's the use case for having a receiver that's not also a transport?

**Comment by alli83** [comment]
The data was already stored and there was just a need to use some messenger concepts in order to facilitate some data processing which consisted in setting up a process using these concepts like the Envelope, the Receiver etc. 

imho, it might be a little bit a peculiar use case but it would be cool to avoid that the presence of these concepts, used rather individually, prevents from finding the transport that we really want to test. 

Thanks for your feedback!

File: src/ZenstruckMessengerTestBundle.php [hunk 1]
```diff
@@ -41,6 +42,15 @@ public function process(ContainerBuilder $container): void
         foreach ($container->findTaggedServiceIds('messenger.receiver') as $id => $tags) {
             $name = $id;
 
+            $class = $container->getDefinition($name)->getClass();
+            if (!$class) {
+                continue;
+            }
```
Comment (kbond) [inline src/ZenstruckMessengerTestBundle.php]:
```suggestion
            if (!$class = $container->getDefinition($name)->getClass()) {
                continue;
            }
```

File: tests/Fixture/Messenger/Receiver/RandomReceiver.php [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+use Symfony\Component\Messenger\Transport\Receiver\ReceiverInterface;
+
+class RandomReceiver implements ReceiverInterface
+{
+    /**
+     * @return Envelope[]
+     *
+     * @throws TransportException
+     */
+    public function get(): iterable
```
Comment (kbond) [inline tests/Fixture/Messenger/Receiver/RandomReceiver.php]:
```suggestion
    public function get(): iterable
```

File: tests/Fixture/Messenger/Receiver/RandomReceiver.php [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+    {
+        yield;
+    }
+
+    /**
+     * @throws TransportException
+     */
+    public function ack(Envelope $envelope): void
```
Comment (kbond) [inline tests/Fixture/Messenger/Receiver/RandomReceiver.php]:
```suggestion
    public function ack(Envelope $envelope): void
```

File: tests/Fixture/Messenger/Receiver/RandomReceiver.php [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+    {
+    }
+
+    /**
+     * @throws TransportException
+     */
+    public function reject(Envelope $envelope): void
```
Comment (kbond) [inline tests/Fixture/Messenger/Receiver/RandomReceiver.php]:
```suggestion
    public function reject(Envelope $envelope): void
```

File: tests/Fixture/Messenger/Receiver/RandomReceiver.php [hunk 5]
```diff
@@ -0,0 +1,23 @@
+<?php
+
+namespace Zenstruck\Messenger\Test\Tests\Fixture\Messenger\Receiver;
+
+use Symfony\Component\Messenger\Envelope;
+use Symfony\Component\Messenger\Exception\TransportException;
+use Symfony\Component\Messenger\Transport\Receiver\ReceiverInterface;
```
Comment (kbond) [inline tests/Fixture/Messenger/Receiver/RandomReceiver.php]:
```suggestion
use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Transport\Receiver\ReceiverInterface;
```

**Comment by kbond** [comment]
Thanks @alli83!
